### This is the Terraform-generated prod-promote.yml workflow for the alma-sapinvoices-prod repository. ###
### If this is a Lambda repo, uncomment the FUNCTION line at the end of the document.                   ###
name: Prod Container Promote
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy:
    name: Prod Container Promote
    uses: mitlibraries/.github/.github/workflows/ecr-shared-promote-prod.yml@main
    secrets: inherit
    with:
      AWS_REGION: "us-east-1"
      GHA_ROLE_STAGE: alma-sapinvoices-gha-stage
      GHA_ROLE_PROD: alma-sapinvoices-gha-prod
      ECR_STAGE: "alma-sapinvoices-stage"
      ECR_PROD: "alma-sapinvoices-prod"
      # FUNCTION: ""
 